### ISSUE TITLE
Cannot run dev

### ISSUE THREAD

**Issue by HFlorina** [CarmenPopoviciu/angular2-go-protractor#3]
When I do : "npm run dev" I get the error :

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev angular2-go@0.0.1
6 info dev angular2-go@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info angular2-go@0.0.1 Failed to exec dev script
9 verbose stack Error: angular2-go@0.0.1 dev: `npm run cpy && npm run tsc`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid angular2-go@0.0.1
11 verbose cwd C:\Users\fhayes\Documents\angular2-go-protractor
12 error Windows_NT 6.1.7601
13 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "dev"
14 error node v4.4.3
15 error npm  v2.15.1
16 error code ELIFECYCLE
17 error angular2-go@0.0.1 dev: `npm run cpy && npm run tsc`
17 error Exit status 1
18 error Failed at the angular2-go@0.0.1 dev script 'npm run cpy && npm run tsc'.
18 error This is most likely a problem with the angular2-go package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run cpy && npm run tsc
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs angular2-go
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls angular2-go
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

I am not sure why is that happening ...
Thanks !

**Comment by alexpopdev** [comment]
As a quick workaround you can install cpy-cli with `npm install --global cpy-cli` and then execute 
`cpy 'src/**/*.html' 'src/**/*.css' dev/src` manually in the root folder, followed by `npm run tsc` and `npm run start` .
My initial guess is that `npm run dev` does not work on Windows, but I plan to test on my Mac as well.
UPDATE: it does work on Linux with Chromium installed so I believe the underlying issue is that it does run on Windows.
